name: PokemonGoSg
favicon: null
layout_spectrum: 0.2572
typography_spectrum: 0.40289
title: Researching the Myths of Pokemon Go
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcb08'
    - '#08224e'
    - '#ffffff'
    - '#bcbdc0'
    - '#ed1c24'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
