name: PokemonGoSg
favicon: null
layout_spectrum: 0.8497984977439046
typography_spectrum: 0.87156518897973
title: Researching the Myths of Pokemon Go
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3075830622110516
  lightness: 0.7523306638468057
  saturation: 0.4022475241217762
  rhythmicContrast: 0.5389758921228349
purpose: []
